default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: contactually_lite
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: contactually_lite
  pool: 5
